'use client'

import {Search} from 'lucide-react'
import {useTranslations} from 'next-intl'
import {useMemo, useState} from 'react'
import {OutputPanel} from '@/components/shared/OutputPanel'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Textarea} from '@/components/ui/textarea'
import {GITIGNORE_TEMPLATES} from '@/data/tools/gitignore-templates'
import {SITE_NAME} from '@/helpers'

const DEFAULT_SELECTED = ['node', 'macos', 'vscode']

interface Preset {
  id: string
  templates: string[]
}

const PRESETS: Preset[] = [
  {
    id: 'web',
    templates: ['node', 'nextjs', 'react', 'vue'],
  },
  {
    id: 'mobile',
    templates: ['swift', 'kotlin', 'dart'],
  },
  {
    id: 'backend',
    templates: [
      'python',
      'django',
      'fastapi',
      'java',
      'go',
      'php',
      'laravel',
      'csharp',
    ],
  },
  {
    id: 'data',
    templates: ['python'],
  },
  {
    id: 'osIde',
    templates: ['macos', 'windows', 'linux', 'vscode', 'jetbrains', 'vim'],
  },
  {
    id: 'infra',
    templates: ['docker', 'terraform', 'kubernetes'],
  },
]

export function GitignoreGeneratorView() {
  const t = useTranslations('config')
  const tGlobal = useTranslations('global')

  const [selected, setSelected] = useState<string[]>(DEFAULT_SELECTED)
  const [custom, setCustom] = useState('')
  const [query, setQuery] = useState('')

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return GITIGNORE_TEMPLATES
    return GITIGNORE_TEMPLATES.filter(tpl => tpl.name.toLowerCase().includes(q))
  }, [query])

  const output = useMemo(() => {
    const seen = new Set<string>()
    const lines: string[] = []

    lines.push(`# Generated by ${SITE_NAME}`)
    lines.push('# https://github.com/github/gitignore')
    lines.push('')

    for (const tpl of GITIGNORE_TEMPLATES) {
      if (!selected.includes(tpl.id)) continue
      lines.push(`# === ${tpl.name} ===`)
      for (const rule of tpl.rules) {
        if (!seen.has(rule)) {
          seen.add(rule)
          lines.push(rule)
        }
      }
      lines.push('')
    }

    if (custom.trim()) {
      lines.push('# === Custom ===')
      lines.push(custom.trim())
    }

    const joined = lines
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd()

    return `${joined}\n`
  }, [selected, custom])

  function toggle(id: string) {
    setSelected(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id],
    )
  }

  function applyPreset(preset: Preset) {
    setSelected(prev => {
      const merged = new Set([...prev, ...preset.templates])
      return Array.from(merged)
    })
  }

  function clearAll() {
    setSelected([])
  }

  // function handleReset() {
  //   setSelected(DEFAULT_SELECTED)
  //   setCustom('')
  //   setQuery('')
  // }

  function handleDownload() {
    const blob = new Blob([output], {type: 'text/plain;charset=utf-8'})
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = '.gitignore'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-5">
      {/* Quick presets */}
      <div className="rounded-2xl border bg-card p-5">
        <div className="mb-3 text-sm font-semibold">
          {t('gitignore-generator.presetsTitle')}
        </div>
        <div className="flex flex-wrap items-center gap-2">
          {PRESETS.map(preset => (
            <Button
              key={preset.id}
              type="button"
              variant="outline"
              size="sm"
              onClick={() => applyPreset(preset)}
            >
              + {t(`gitignore-generator.presets.${preset.id}`)}
            </Button>
          ))}
          {selected.length > 0 && (
            <button
              type="button"
              onClick={clearAll}
              className="ml-2 text-xs text-muted-foreground hover:text-foreground"
            >
              {tGlobal('clear')}
            </button>
          )}
        </div>
      </div>

      {/* Templates with search */}
      <div className="rounded-2xl border bg-card p-5">
        <div className="mb-4 flex items-center gap-3">
          <div className="relative flex-1">
            <Search className="pointer-events-none absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder={t('gitignore-generator.searchPlaceholder')}
              className="pl-9"
            />
          </div>
          <div className="shrink-0 text-xs text-muted-foreground">
            {t('gitignore-generator.selectedCount', {
              count: selected.length,
            })}
          </div>
        </div>

        {filtered.length > 0 ? (
          <div className="grid max-h-70 grid-cols-2 gap-2 overflow-auto pr-1 sm:grid-cols-3 md:grid-cols-4">
            {filtered.map(tpl => {
              const active = selected.includes(tpl.id)
              return (
                <button
                  key={tpl.id}
                  type="button"
                  onClick={() => toggle(tpl.id)}
                  className={`rounded-2xl border px-3 py-2 text-left text-sm transition ${
                    active
                      ? 'border-primary/40 bg-primary/10 font-medium'
                      : 'border-border bg-background hover:border-primary/60'
                  }`}
                >
                  {tpl.name}
                </button>
              )
            })}
          </div>
        ) : (
          <div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">
            {t('gitignore-generator.emptySearch')}
          </div>
        )}
      </div>

      {/* Custom rules */}
      <div className="space-y-2 rounded-2xl border bg-card p-5">
        <label htmlFor="gi-custom" className="text-sm font-medium">
          {t('gitignore-generator.customLabel')}
        </label>
        <Textarea
          id="gi-custom"
          value={custom}
          onChange={e => setCustom(e.target.value)}
          placeholder={t('gitignore-generator.customPlaceholder')}
          className="h-24 min-h-24 font-mono text-sm"
        />
      </div>

      {/* Toolbar
      <div className="flex flex-wrap items-center gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleDownload}
        >
          <Download className="mr-1.5 h-3.5 w-3.5" />
          {t('gitignore-generator.download')}
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleReset}
          className="text-destructive hover:text-destructive"
        >
          <X className="mr-1.5 h-3.5 w-3.5" />
          {tGlobal('reset')}
        </Button>
      </div>
      */}

      {/* Output */}
      <OutputPanel
        title={t('gitignore-generator.outputTitle')}
        value={output}
        heightClass="min-h-[160px] max-h-150"
        contentClassName="font-mono text-xs"
        onDownload={handleDownload}
      />

      <p className="text-center text-xs text-muted-foreground">
        {t('gitignore-generator.note')}
      </p>
    </div>
  )
}
